baseURL = 'https://podgepig.github.io/'
locale = 'en-uk'
title = 'Applications of Pure Mathematics to Finance'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  background_color_class = "bg-white"
  description = "by Padraig Hill"